-keep class com.k2fsa.sherpa.onnx.** { *; }
-keep class com.tencent.mmkv.** { *; }
-keep class * implements android.os.Parcelable { public static final ** CREATOR; }
-keepclasseswithmembernames class * { native <methods>; }
