// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// 引擎总体状态（规格 §4 `EngineStatus`）。
///
/// [state] 取值：`noModel` / `loading` / `ready` / `reloading` / `error`；
/// [online] 取值：`off` / `ready` / `noKey` / `error`。
class EngineStatusDto {
  EngineStatusDto({
    required this.state,
    this.modelId,
    required this.sampleRate,
    required this.speakers,
    required this.online,
  });

  /// 引擎状态机（core.EngineState 的富化映射）。
  String state;

  /// 使用中的模型 id（未安装/未加载时为 null）。
  String? modelId;

  /// 合成采样率（Hz；未知为 0）。
  int sampleRate;

  /// 可用音色数（= 当前模型音色池大小；未知为 0）。
  int speakers;

  /// 在线朗读状态。
  String online;

  List<Object?> _toList() {
    return <Object?>[
      state,
      modelId,
      sampleRate,
      speakers,
      online,
    ];
  }

  Object encode() {
    return _toList();  }

  static EngineStatusDto decode(Object result) {
    result as List<Object?>;
    return EngineStatusDto(
      state: result[0]! as String,
      modelId: result[1] as String?,
      sampleRate: result[2]! as int,
      speakers: result[3]! as int,
      online: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EngineStatusDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(modelId, other.modelId) && _deepEquals(sampleRate, other.sampleRate) && _deepEquals(speakers, other.speakers) && _deepEquals(online, other.online);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EngineStatusDto(state: $state, modelId: $modelId, sampleRate: $sampleRate, speakers: $speakers, online: $online)';
  }
}

/// 模型条目（规格 §4 `ModelInfo`）。
class ModelDto {
  ModelDto({
    required this.id,
    required this.label,
    required this.note,
    required this.downloadBytes,
    required this.extractedBytes,
    required this.installed,
    required this.active,
    required this.recommended,
  });

  String id;

  /// 清单展示名。
  String label;

  /// 清单说明（用户可读文案）。
  String note;

  /// 下载包实测字节（清单字段；Long）。
  int downloadBytes;

  /// 解压后实测字节（清单字段；Long）。
  int extractedBytes;

  /// 已安装（`.completed` 哨兵 + 模型文件双校验）。
  bool installed;

  /// 使用中（已安装且为当前 modelId）。
  bool active;

  /// 清单推荐档。
  bool recommended;

  List<Object?> _toList() {
    return <Object?>[
      id,
      label,
      note,
      downloadBytes,
      extractedBytes,
      installed,
      active,
      recommended,
    ];
  }

  Object encode() {
    return _toList();  }

  static ModelDto decode(Object result) {
    result as List<Object?>;
    return ModelDto(
      id: result[0]! as String,
      label: result[1]! as String,
      note: result[2]! as String,
      downloadBytes: result[3]! as int,
      extractedBytes: result[4]! as int,
      installed: result[5]! as bool,
      active: result[6]! as bool,
      recommended: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ModelDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(label, other.label) && _deepEquals(note, other.note) && _deepEquals(downloadBytes, other.downloadBytes) && _deepEquals(extractedBytes, other.extractedBytes) && _deepEquals(installed, other.installed) && _deepEquals(active, other.active) && _deepEquals(recommended, other.recommended);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ModelDto(id: $id, label: $label, note: $note, downloadBytes: $downloadBytes, extractedBytes: $extractedBytes, installed: $installed, active: $active, recommended: $recommended)';
  }
}

/// 下载进度（规格 §4 `DownloadProgress`）。
///
/// [phase] 取值：`idle` / `probe` / `download` / `verify` / `extract` / `promote` / `done` / `error`。
class DownloadStateDto {
  DownloadStateDto({
    required this.modelId,
    required this.received,
    required this.total,
    required this.phase,
  });

  String modelId;

  int received;

  int total;

  String phase;

  List<Object?> _toList() {
    return <Object?>[
      modelId,
      received,
      total,
      phase,
    ];
  }

  Object encode() {
    return _toList();  }

  static DownloadStateDto decode(Object result) {
    result as List<Object?>;
    return DownloadStateDto(
      modelId: result[0]! as String,
      received: result[1]! as int,
      total: result[2]! as int,
      phase: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DownloadStateDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(modelId, other.modelId) && _deepEquals(received, other.received) && _deepEquals(total, other.total) && _deepEquals(phase, other.phase);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DownloadStateDto(modelId: $modelId, received: $received, total: $total, phase: $phase)';
  }
}

/// 音色条目（规格 §4 `VoiceInfo`）。
class VoiceDto {
  VoiceDto({
    required this.id,
    required this.name,
    required this.lang,
    required this.isNarrator,
  });

  String id;

  /// 中文展示名（ADR-007）。
  String name;

  /// `zh` 中文（优先展示）/ `en` 英文（折叠展示）。
  String lang;

  /// 是否为当前全局旁白。
  bool isNarrator;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      lang,
      isNarrator,
    ];
  }

  Object encode() {
    return _toList();  }

  static VoiceDto decode(Object result) {
    result as List<Object?>;
    return VoiceDto(
      id: result[0]! as String,
      name: result[1]! as String,
      lang: result[2]! as String,
      isNarrator: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VoiceDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(lang, other.lang) && _deepEquals(isNarrator, other.isNarrator);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VoiceDto(id: $id, name: $name, lang: $lang, isNarrator: $isNarrator)';
  }
}

/// 应用配置（规格 §4 `AppConfig`）。
class ConfigDto {
  ConfigDto({
    required this.speed,
    required this.onlineEnabled,
    required this.tokenPlanAccepted,
    required this.keyKind,
    required this.apiKeyMasked,
    required this.baseUrl,
    required this.allowMobileData,
    required this.customMirror,
  });

  /// 语速倍数（默认 1.0）。
  double speed;

  /// 在线朗读总开关（默认关）。
  bool onlineEnabled;

  /// Token Plan 风险确认是否已通过。
  bool tokenPlanAccepted;

  /// `billing` 按量计费 / `plan` Token Plan。
  String keyKind;

  /// 脱敏后的密钥（仅回显，永不返回明文）。
  String apiKeyMasked;

  /// 生效 Base URL（自定义为空时按 keyKind 自动解析）。
  String baseUrl;

  /// 允许使用数据流量（默认关）。
  bool allowMobileData;

  /// 自定义下载镜像基地址（空 = 官方源）。
  String customMirror;

  List<Object?> _toList() {
    return <Object?>[
      speed,
      onlineEnabled,
      tokenPlanAccepted,
      keyKind,
      apiKeyMasked,
      baseUrl,
      allowMobileData,
      customMirror,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConfigDto decode(Object result) {
    result as List<Object?>;
    return ConfigDto(
      speed: result[0]! as double,
      onlineEnabled: result[1]! as bool,
      tokenPlanAccepted: result[2]! as bool,
      keyKind: result[3]! as String,
      apiKeyMasked: result[4]! as String,
      baseUrl: result[5]! as String,
      allowMobileData: result[6]! as bool,
      customMirror: result[7]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConfigDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(speed, other.speed) && _deepEquals(onlineEnabled, other.onlineEnabled) && _deepEquals(tokenPlanAccepted, other.tokenPlanAccepted) && _deepEquals(keyKind, other.keyKind) && _deepEquals(apiKeyMasked, other.apiKeyMasked) && _deepEquals(baseUrl, other.baseUrl) && _deepEquals(allowMobileData, other.allowMobileData) && _deepEquals(customMirror, other.customMirror);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConfigDto(speed: $speed, onlineEnabled: $onlineEnabled, tokenPlanAccepted: $tokenPlanAccepted, keyKind: $keyKind, apiKeyMasked: $apiKeyMasked, baseUrl: $baseUrl, allowMobileData: $allowMobileData, customMirror: $customMirror)';
  }
}

/// 引擎事件（规格 §4 `EngineEvent`）。
class EngineEventDto {
  EngineEventDto({
    required this.type,
    required this.dataJson,
  });

  /// `status` / `progress` / `model` / `error`。
  String type;

  /// 事件数据：JSON 对象串（键与规格 §4 各事件 data 一致）。
  String dataJson;

  List<Object?> _toList() {
    return <Object?>[
      type,
      dataJson,
    ];
  }

  Object encode() {
    return _toList();  }

  static EngineEventDto decode(Object result) {
    result as List<Object?>;
    return EngineEventDto(
      type: result[0]! as String,
      dataJson: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EngineEventDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(dataJson, other.dataJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EngineEventDto(type: $type, dataJson: $dataJson)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is EngineStatusDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ModelDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is DownloadStateDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is VoiceDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is ConfigDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is EngineEventDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return EngineStatusDto.decode(readValue(buffer)!);
      case 130:
        return ModelDto.decode(readValue(buffer)!);
      case 131:
        return DownloadStateDto.decode(readValue(buffer)!);
      case 132:
        return VoiceDto.decode(readValue(buffer)!);
      case 133:
        return ConfigDto.decode(readValue(buffer)!);
      case 134:
        return EngineEventDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// App → 引擎（宿主侧实现，Flutter 调用）。
class EngineHostApi {
  /// Constructor for [EngineHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  EngineHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  /// 引擎总体状态。
  Future<EngineStatusDto> status() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as EngineStatusDto;
  }

  /// 模型清单（清单驱动：远程 → 缓存 → 内置兜底，含自定义镜像）。
  Future<List<ModelDto>> models() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.models$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<ModelDto>();
  }

  /// 开始下载（前台服务；已安装则忽略）。
  Future<void> startDownload(String modelId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.startDownload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[modelId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 取消下载（停服务 → 引擎侧 onDestroy 取消并清理残包）。
  Future<void> cancelDownload() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.cancelDownload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 删除已安装模型（下载进行中的模型拒绝删除）。
  Future<void> deleteModel(String modelId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.deleteModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[modelId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 设为使用中（未安装则忽略，与规格 Mock 语义一致）。
  Future<void> setActiveModel(String modelId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.setActiveModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[modelId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 当前模型音色池（中文优先，英文折叠由界面负责）。
  Future<List<VoiceDto>> voices() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.voices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<VoiceDto>();
  }

  /// 设置全局旁白音色（试听**不**走这里）。
  Future<void> setNarratorVoice(String voiceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.setNarratorVoice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[voiceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 试听指定音色——**不改变全局旁白**（试听失败静默回退，见引擎 PreviewPlayer）。
  Future<void> preview(String text, String voiceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.preview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[text, voiceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 停止试听。
  Future<void> stopPreview() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.stopPreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 读取配置。
  Future<ConfigDto> config() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.config$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ConfigDto;
  }

  /// 更新配置（null = 不改；写入后广播引擎热重载）。
  Future<void> updateConfig({double? speed, bool? onlineEnabled, bool? allowMobileData, String? keyKind, String? apiKey, String? baseUrl, String? customMirror, bool? tokenPlanAccepted, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.updateConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[speed, onlineEnabled, allowMobileData, keyKind, apiKey, baseUrl, customMirror, tokenPlanAccepted]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 最近日志（桥接观测到的引擎事件；新的在下）。
  Future<List<String>> recentLogs() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.recentLogs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// 性能计数清零（丢块计数等）。
  Future<void> clearPerfCounters() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.clearPerfCounters$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 校验密钥：null = 通过；否则平台方原始错误摘要（≤200 字）。
  Future<String?> validateKey(String keyKind, String apiKey) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ebook2tts.EngineHostApi.validateKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[keyKind, apiKey]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }
}

/// 引擎 → App（Flutter 侧实现，宿主调用）。
abstract class EngineEventApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// 事件推送（type: status / progress / model / error）。
  void onEvent(EngineEventDto event);

  static void setUp(EngineEventApi? api, {
    BinaryMessenger? binaryMessenger, 
    String messageChannelSuffix = '',
  }) 
{
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ebook2tts.EngineEventApi.onEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final EngineEventDto arg_event = args[0]! as EngineEventDto;
          try {
            api.onEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
