// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.kermond.ebook2tts

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object EngineBridgePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * 引擎总体状态（规格 §4 `EngineStatus`）。
 *
 * [state] 取值：`noModel` / `loading` / `ready` / `reloading` / `error`；
 * [online] 取值：`off` / `ready` / `noKey` / `error`。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EngineStatusDto (
  /** 引擎状态机（core.EngineState 的富化映射）。 */
  val state: String,
  /** 使用中的模型 id（未安装/未加载时为 null）。 */
  val modelId: String? = null,
  /** 合成采样率（Hz；未知为 0）。 */
  val sampleRate: Long,
  /** 可用音色数（= 当前模型音色池大小；未知为 0）。 */
  val speakers: Long,
  /** 在线朗读状态。 */
  val online: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EngineStatusDto {
      val state = pigeonVar_list[0] as String
      val modelId = pigeonVar_list[1] as String?
      val sampleRate = pigeonVar_list[2] as Long
      val speakers = pigeonVar_list[3] as Long
      val online = pigeonVar_list[4] as String
      return EngineStatusDto(state, modelId, sampleRate, speakers, online)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      modelId,
      sampleRate,
      speakers,
      online,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EngineStatusDto
    return EngineBridgePigeonUtils.deepEquals(this.state, other.state) && EngineBridgePigeonUtils.deepEquals(this.modelId, other.modelId) && EngineBridgePigeonUtils.deepEquals(this.sampleRate, other.sampleRate) && EngineBridgePigeonUtils.deepEquals(this.speakers, other.speakers) && EngineBridgePigeonUtils.deepEquals(this.online, other.online)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.state)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.modelId)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.sampleRate)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.speakers)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.online)
    return result
  }
  override fun toString(): String {
    return "EngineStatusDto(state=$state, modelId=$modelId, sampleRate=$sampleRate, speakers=$speakers, online=$online)"
  }
}

/**
 * 模型条目（规格 §4 `ModelInfo`）。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ModelDto (
  val id: String,
  /** 清单展示名。 */
  val label: String,
  /** 清单说明（用户可读文案）。 */
  val note: String,
  /** 下载包实测字节（清单字段；Long）。 */
  val downloadBytes: Long,
  /** 解压后实测字节（清单字段；Long）。 */
  val extractedBytes: Long,
  /** 已安装（`.completed` 哨兵 + 模型文件双校验）。 */
  val installed: Boolean,
  /** 使用中（已安装且为当前 modelId）。 */
  val active: Boolean,
  /** 清单推荐档。 */
  val recommended: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ModelDto {
      val id = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val note = pigeonVar_list[2] as String
      val downloadBytes = pigeonVar_list[3] as Long
      val extractedBytes = pigeonVar_list[4] as Long
      val installed = pigeonVar_list[5] as Boolean
      val active = pigeonVar_list[6] as Boolean
      val recommended = pigeonVar_list[7] as Boolean
      return ModelDto(id, label, note, downloadBytes, extractedBytes, installed, active, recommended)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      label,
      note,
      downloadBytes,
      extractedBytes,
      installed,
      active,
      recommended,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ModelDto
    return EngineBridgePigeonUtils.deepEquals(this.id, other.id) && EngineBridgePigeonUtils.deepEquals(this.label, other.label) && EngineBridgePigeonUtils.deepEquals(this.note, other.note) && EngineBridgePigeonUtils.deepEquals(this.downloadBytes, other.downloadBytes) && EngineBridgePigeonUtils.deepEquals(this.extractedBytes, other.extractedBytes) && EngineBridgePigeonUtils.deepEquals(this.installed, other.installed) && EngineBridgePigeonUtils.deepEquals(this.active, other.active) && EngineBridgePigeonUtils.deepEquals(this.recommended, other.recommended)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.id)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.label)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.note)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.downloadBytes)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.extractedBytes)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.installed)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.active)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.recommended)
    return result
  }
  override fun toString(): String {
    return "ModelDto(id=$id, label=$label, note=$note, downloadBytes=$downloadBytes, extractedBytes=$extractedBytes, installed=$installed, active=$active, recommended=$recommended)"
  }
}

/**
 * 下载进度（规格 §4 `DownloadProgress`）。
 *
 * [phase] 取值：`idle` / `probe` / `download` / `verify` / `extract` / `promote` / `done` / `error`。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DownloadStateDto (
  val modelId: String,
  val received: Long,
  val total: Long,
  val phase: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadStateDto {
      val modelId = pigeonVar_list[0] as String
      val received = pigeonVar_list[1] as Long
      val total = pigeonVar_list[2] as Long
      val phase = pigeonVar_list[3] as String
      return DownloadStateDto(modelId, received, total, phase)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      modelId,
      received,
      total,
      phase,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DownloadStateDto
    return EngineBridgePigeonUtils.deepEquals(this.modelId, other.modelId) && EngineBridgePigeonUtils.deepEquals(this.received, other.received) && EngineBridgePigeonUtils.deepEquals(this.total, other.total) && EngineBridgePigeonUtils.deepEquals(this.phase, other.phase)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.modelId)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.received)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.total)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.phase)
    return result
  }
  override fun toString(): String {
    return "DownloadStateDto(modelId=$modelId, received=$received, total=$total, phase=$phase)"
  }
}

/**
 * 音色条目（规格 §4 `VoiceInfo`）。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VoiceDto (
  val id: String,
  /** 中文展示名（ADR-007）。 */
  val name: String,
  /** `zh` 中文（优先展示）/ `en` 英文（折叠展示）。 */
  val lang: String,
  /** 是否为当前全局旁白。 */
  val isNarrator: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VoiceDto {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val lang = pigeonVar_list[2] as String
      val isNarrator = pigeonVar_list[3] as Boolean
      return VoiceDto(id, name, lang, isNarrator)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      lang,
      isNarrator,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VoiceDto
    return EngineBridgePigeonUtils.deepEquals(this.id, other.id) && EngineBridgePigeonUtils.deepEquals(this.name, other.name) && EngineBridgePigeonUtils.deepEquals(this.lang, other.lang) && EngineBridgePigeonUtils.deepEquals(this.isNarrator, other.isNarrator)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.id)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.name)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.lang)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.isNarrator)
    return result
  }
  override fun toString(): String {
    return "VoiceDto(id=$id, name=$name, lang=$lang, isNarrator=$isNarrator)"
  }
}

/**
 * 应用配置（规格 §4 `AppConfig`）。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ConfigDto (
  /** 语速倍数（默认 1.0）。 */
  val speed: Double,
  /** 在线朗读总开关（默认关）。 */
  val onlineEnabled: Boolean,
  /** Token Plan 风险确认是否已通过。 */
  val tokenPlanAccepted: Boolean,
  /** `billing` 按量计费 / `plan` Token Plan。 */
  val keyKind: String,
  /** 脱敏后的密钥（仅回显，永不返回明文）。 */
  val apiKeyMasked: String,
  /** 生效 Base URL（自定义为空时按 keyKind 自动解析）。 */
  val baseUrl: String,
  /** 允许使用数据流量（默认关）。 */
  val allowMobileData: Boolean,
  /** 自定义下载镜像基地址（空 = 官方源）。 */
  val customMirror: String,
  /** 「AI 角色音色」开关（RQ-507；默认开，仅在线时有意义）。 */
  val roleVoiceEnabled: Boolean,
  /** 已建档角色数（诊断展示）。 */
  val roleCount: Long,
  /** 角色精标成功次数（文本用量粗估，诊断展示）。 */
  val roleRefineCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConfigDto {
      val speed = pigeonVar_list[0] as Double
      val onlineEnabled = pigeonVar_list[1] as Boolean
      val tokenPlanAccepted = pigeonVar_list[2] as Boolean
      val keyKind = pigeonVar_list[3] as String
      val apiKeyMasked = pigeonVar_list[4] as String
      val baseUrl = pigeonVar_list[5] as String
      val allowMobileData = pigeonVar_list[6] as Boolean
      val customMirror = pigeonVar_list[7] as String
      val roleVoiceEnabled = pigeonVar_list[8] as Boolean
      val roleCount = pigeonVar_list[9] as Long
      val roleRefineCount = pigeonVar_list[10] as Long
      return ConfigDto(speed, onlineEnabled, tokenPlanAccepted, keyKind, apiKeyMasked, baseUrl, allowMobileData, customMirror, roleVoiceEnabled, roleCount, roleRefineCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      speed,
      onlineEnabled,
      tokenPlanAccepted,
      keyKind,
      apiKeyMasked,
      baseUrl,
      allowMobileData,
      customMirror,
      roleVoiceEnabled,
      roleCount,
      roleRefineCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConfigDto
    return EngineBridgePigeonUtils.deepEquals(this.speed, other.speed) && EngineBridgePigeonUtils.deepEquals(this.onlineEnabled, other.onlineEnabled) && EngineBridgePigeonUtils.deepEquals(this.tokenPlanAccepted, other.tokenPlanAccepted) && EngineBridgePigeonUtils.deepEquals(this.keyKind, other.keyKind) && EngineBridgePigeonUtils.deepEquals(this.apiKeyMasked, other.apiKeyMasked) && EngineBridgePigeonUtils.deepEquals(this.baseUrl, other.baseUrl) && EngineBridgePigeonUtils.deepEquals(this.allowMobileData, other.allowMobileData) && EngineBridgePigeonUtils.deepEquals(this.customMirror, other.customMirror) && EngineBridgePigeonUtils.deepEquals(this.roleVoiceEnabled, other.roleVoiceEnabled) && EngineBridgePigeonUtils.deepEquals(this.roleCount, other.roleCount) && EngineBridgePigeonUtils.deepEquals(this.roleRefineCount, other.roleRefineCount)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.speed)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.onlineEnabled)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.tokenPlanAccepted)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.keyKind)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.apiKeyMasked)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.baseUrl)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.allowMobileData)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.customMirror)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.roleVoiceEnabled)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.roleCount)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.roleRefineCount)
    return result
  }
  override fun toString(): String {
    return "ConfigDto(speed=$speed, onlineEnabled=$onlineEnabled, tokenPlanAccepted=$tokenPlanAccepted, keyKind=$keyKind, apiKeyMasked=$apiKeyMasked, baseUrl=$baseUrl, allowMobileData=$allowMobileData, customMirror=$customMirror, roleVoiceEnabled=$roleVoiceEnabled, roleCount=$roleCount, roleRefineCount=$roleRefineCount)"
  }
}

/**
 * 引擎事件（规格 §4 `EngineEvent`）。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EngineEventDto (
  /** `status` / `progress` / `model` / `error`。 */
  val type: String,
  /** 事件数据：JSON 对象串（键与规格 §4 各事件 data 一致）。 */
  val dataJson: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EngineEventDto {
      val type = pigeonVar_list[0] as String
      val dataJson = pigeonVar_list[1] as String
      return EngineEventDto(type, dataJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      dataJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EngineEventDto
    return EngineBridgePigeonUtils.deepEquals(this.type, other.type) && EngineBridgePigeonUtils.deepEquals(this.dataJson, other.dataJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.type)
    result = 31 * result + EngineBridgePigeonUtils.deepHash(this.dataJson)
    return result
  }
  override fun toString(): String {
    return "EngineEventDto(type=$type, dataJson=$dataJson)"
  }
}
private open class EngineBridgePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EngineStatusDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModelDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadStateDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VoiceDto.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConfigDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EngineEventDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EngineStatusDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ModelDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DownloadStateDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is VoiceDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ConfigDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is EngineEventDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * App → 引擎（宿主侧实现，Flutter 调用）。
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface EngineHostApi {
  /** 引擎总体状态。 */
  suspend fun status(): EngineStatusDto
  /** 模型清单（清单驱动：远程 → 缓存 → 内置兜底，含自定义镜像）。 */
  suspend fun models(): List<ModelDto>
  /** 开始下载（前台服务；已安装则忽略）。 */
  suspend fun startDownload(modelId: String)
  /** 取消下载（停服务 → 引擎侧 onDestroy 取消并清理残包）。 */
  suspend fun cancelDownload()
  /** 删除已安装模型（下载进行中的模型拒绝删除）。 */
  suspend fun deleteModel(modelId: String)
  /** 设为使用中（未安装则忽略，与规格 Mock 语义一致）。 */
  suspend fun setActiveModel(modelId: String)
  /** 当前模型音色池（中文优先，英文折叠由界面负责）。 */
  suspend fun voices(): List<VoiceDto>
  /** 设置全局旁白音色（试听**不**走这里）。 */
  suspend fun setNarratorVoice(voiceId: String)
  /** 试听指定音色——**不改变全局旁白**（试听失败静默回退，见引擎 PreviewPlayer）。 */
  suspend fun preview(text: String, voiceId: String)
  /** 停止试听。 */
  suspend fun stopPreview()
  /** 读取配置。 */
  suspend fun config(): ConfigDto
  /** 更新配置（null = 不改；写入后广播引擎热重载）。 */
  suspend fun updateConfig(speed: Double?, onlineEnabled: Boolean?, allowMobileData: Boolean?, keyKind: String?, apiKey: String?, baseUrl: String?, customMirror: String?, tokenPlanAccepted: Boolean?, roleVoiceEnabled: Boolean?)
  /** 最近日志（桥接观测到的引擎事件；新的在下）。 */
  suspend fun recentLogs(): List<String>
  /** 性能计数清零（丢块计数等）。 */
  suspend fun clearPerfCounters()
  /** 校验密钥：null = 通过；否则平台方原始错误摘要（≤200 字）。 */
  suspend fun validateKey(keyKind: String, apiKey: String): String?

  companion object {
    /** The codec used by EngineHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      EngineBridgePigeonCodec()
    }
    /** Sets up an instance of `EngineHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EngineHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.status$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.status())
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.models$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.models())
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.startDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modelIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.startDownload(modelIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.cancelDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.cancelDownload()
                listOf(null)
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.deleteModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modelIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.deleteModel(modelIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.setActiveModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modelIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setActiveModel(modelIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.voices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.voices())
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.setNarratorVoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val voiceIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setNarratorVoice(voiceIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.preview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val voiceIdArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.preview(textArg, voiceIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.stopPreview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.stopPreview()
                listOf(null)
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.config$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.config())
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.updateConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val speedArg = args[0] as Double?
            val onlineEnabledArg = args[1] as Boolean?
            val allowMobileDataArg = args[2] as Boolean?
            val keyKindArg = args[3] as String?
            val apiKeyArg = args[4] as String?
            val baseUrlArg = args[5] as String?
            val customMirrorArg = args[6] as String?
            val tokenPlanAcceptedArg = args[7] as Boolean?
            val roleVoiceEnabledArg = args[8] as Boolean?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.updateConfig(speedArg, onlineEnabledArg, allowMobileDataArg, keyKindArg, apiKeyArg, baseUrlArg, customMirrorArg, tokenPlanAcceptedArg, roleVoiceEnabledArg)
                listOf(null)
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.recentLogs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.recentLogs())
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.clearPerfCounters$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.clearPerfCounters()
                listOf(null)
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ebook2tts.EngineHostApi.validateKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyKindArg = args[0] as String
            val apiKeyArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.validateKey(keyKindArg, apiKeyArg))
              } catch (exception: Throwable) {
                EngineBridgePigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * 引擎 → App（Flutter 侧实现，宿主调用）。
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class EngineEventApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by EngineEventApi. */
    val codec: MessageCodec<Any?> by lazy {
      EngineBridgePigeonCodec()
    }
  }
  /** 事件推送（type: status / progress / model / error）。 */
  suspend fun onEvent(eventArg: EngineEventDto)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.ebook2tts.EngineEventApi.onEvent$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(EngineBridgePigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
